spring:
  application:
    name: face-id
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:faceid;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=faceid;encrypt=true;trustServerCertificate=true
    username: sa
    password: ${DB_PASSWORD_PROD} # Referencia a uma variavel de ambiente
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Configuracao do Springdoc OpenAPI
springdoc:
  packagesToScan: com.faceid.controller # Garante que o Springdoc escaneia seus controladores
  swagger-ui:
    path: /swagger-ui.html # Garante que o caminho do Swagger UI e o padrao
