spring:
  profiles:
    active: ${SPRING_PROFILE:dev} # Se não definido, usa 'dev'

springdoc:
  packagesToScan: com.faceid.controller
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true} # true no dev, false no prod
    path: /swagger-ui.html

opencv:
  haarcascade:
    path: classpath:haarcascade_frontalface_alt.xml

app:
  image:
    storage:
      path: ${IMAGE_STORAGE_PATH:./uploads/faces}
