spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate   # em prod não se usa update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect

springdoc:
  swagger-ui:
    enabled: false
