spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://prod-server:1433;databaseName=faceid_prod;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:prod_user}
    password: ${DB_PASSWORD:ProdSecret123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate   # em prod não se usa update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect

springdoc:
  swagger-ui:
    enabled: false
