spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=faceid;encrypt=true;trustServerCertificate=true
    username: sa
    password: YourStrong!Passw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update   # (dev: update, prod: validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
    show-sql: true
