spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=faceid;encrypt=true;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourStrong!Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
