spring:
  profiles:
    active: ${SPRING_PROFILE:dev}  # padrão é 'dev'

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true

springdoc:
  packagesToScan: com.faceid.controller
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: /swagger-ui.html

opencv:
  haarcascade:
    path: classpath:haarcascade_frontalface_alt.xml

app:
  image:
    storage:
      path: ${IMAGE_STORAGE_PATH:./uploads/faces}
